name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * 1' # Executa toda segunda-feira às 8h

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run npm audit
        run: npm audit --production
      
      - name: Run ESLint
        run: npm run lint
      
      # Usando Snyk para análise avançada de vulnerabilidades
      - name: Snyk Setup
        uses: snyk/actions/setup@master
      
      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: ${{ env.SNYK_TOKEN != '' }}
      
      - name: Snyk Test
        run: snyk test --severity-threshold=high
        if: ${{ env.SNYK_TOKEN != '' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      
      # Verifica se há variáveis de ambiente expostas acidentalmente
      - name: Check for exposed credentials
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 